[package]
name = "cfgenius"
version = "0.1.0"
authors = ["daemonw"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
rust-crypto = "0.2.36"
rand = "0.7.3"